### ISSUE TITLE
Blesta ISPAPI registrar module Not working

### ISSUE THREAD

**Issue by zahid-10corp** [centralnicgroup-opensource/rtldev-middleware-blesta-ispapi-registrar#101]
After installing the domain manager the Hexonet registrar module is no longer being recognised as a registrar module

https://www.blesta.com/forums/index.php?/topic/15960-after-installing-the-domain-manager-the-hexonet-registrar-module-is-no-longer-being-recognised-as-a-registrar-module/

**Comment by KaiSchwarz-cnic** [comment]
@zahid-10corp are you using the latest version of the module?
https://github.com/centralnicgroup-opensource/rtldev-middleware-blesta-ispapi-registrar/releases/tag/v3.0.5

Would you mind providing details regarding your platform?
* Blesta version in use
* PHP version in use

ty

**Comment by KaiSchwarz-cnic** [comment]
imho this is just related to an outdated version. we made our module Blesta 5 ready, just few features are missing yet.
Feel free to follow-up in case you're still having this issue after upgrading to the latest version of our module.

ty

**Comment by zahid-10corp** [comment]
Installed Version 5.6.0-b1 with PHP 7.4
ERROR: 423 Service is not active!
The user and password combination appear to be invalid, or your Ispapi account may not be configured to allow API access

**Comment by KaiSchwarz-cnic** [comment]
Not sure where this error exactly happens as you are not sharing many details. Screenshot available maybe?

**Comment by zahid-10corp** [comment]
``[url=https://ibb.co/8D2n1JR][img]https://i.ibb.co/nsfqxTV/Settings-Company-Modules-Add-Ispapi-Account-My-Company.png[/img][/url]
[url=https://nonprofitlight.com/ia/sioux-city/goodwill-of-the-great-plains]goodwill sioux city[/url]

**Comment by KaiSchwarz-cnic** [comment]
Ok ty. We will check that.

**Comment by zahid-10corp** [comment]
please review namesilo Features with new module https://github.com/blesta/module-namesilo

**Comment by KaiSchwarz-cnic** [comment]
Patching a bug is fine, but extending / adding features has currently no priority. 2023 may change things, nothing I can promise. We are accepting Pull Requests btw.

**Comment by KaiSchwarz-cnic** [comment]
latest version is patching this.

A while ago we moved our OT&E System / Sandbox system to another Data Center and separated it to non-production servers as well. With that step the API endpoint url for the OT&E System changed. We reflected this already in our API Connector Library, but missed upgrading it in Blesta.

HTH
Kai

**Comment by zahid-10corp** [comment]
Now I can contend with API. and order domain but it not showing my domain and even its not register with account-ote.hexonet.net check screenshot
![Client-1500-Profile-My-Company](https://user-images.githubusercontent.com/116925641/203974128-76f9f204-7679-464b-bf52-69d8fbba9ca4.png)
![Domains-TLDs-My-Company](https://user-images.githubusercontent.com/116925641/203974133-5640a5b7-7db4-49bf-9ece-19489ee049bf.png)
![Billing-Overview-My-Company](https://user-images.githubusercontent.com/116925641/203974137-f880769d-092b-405c-8fc0-6ccac837ebad.png)
![Client-1500-My-Company](https://user-images.githubusercontent.com/116925641/203974141-424b1821-84c8-45d9-a98e-9fcc2a85cbcc.png)

**Comment by zahid-10corp** [comment]
API Command maybe changes. Domain Register not working 
![Client-1500-My-Company](https://user-images.githubusercontent.com/116925641/203976292-ec5ef208-24f3-4c91-89e8-0863ee557ae5.png)
![Client-1500-Profile-My-Company](https://user-images.githubusercontent.com/116925641/203976299-b7ea1a98-7a48-4fdc-a87d-fa8774d03c18.png)
![Domains-TLDs-My-Company](https://user-images.githubusercontent.com/116925641/203976301-a46e68aa-2f96-4b2d-9ae4-022ad5f49bfe.png)
![Billing-Overview-My-Company](https://user-images.githubusercontent.com/116925641/203976303-785df873-1205-4520-8279-8d2aff3d8e9a.png)
![Client-1500-Manage-Service-My-Company](https://user-images.githubusercontent.com/116925641/203976306-4d686a2b-a462-4bb4-a777-4c638067f8ca.png)

**Comment by KaiSchwarz-cnic** [comment]
Will have an eye on this on monday. Busy days.

**Comment by KaiSchwarz-cnic** [comment]
Cron job set up?
https://docs.blesta.com/display/user/Installing+Blesta#InstallingBlesta-5.SetupaCronJob

**Comment by domaingood** [comment]
Yes  The cron run every 5 minutes.
Attempting to run all tasks for My Company.
All tasks have been completed.
Attempting to run all system tasks.
All system tasks have been completed.

**Comment by domaingood** [comment]
Now I have fix issue Why dont show Error by Email/message. Domain is now registed. Domain Option Missing

[Client-1500
![203976299-b7ea1a98-7a48-4fdc-a87d-fa8774d03c18](https://user-images.githubusercontent.com/30205596/204061631-25f24811-ff23-4631-88d7-730fd4179a91.png)
-Manage-Service-My-Company.webm](https://user-images.githubusercontent.com/30205596/204061522-d599182d-4126-4c9c-ab2c-f2b39a25aef1.webm)
[Dashboard-My-Company.webm](https://user-images.githubusercontent.com/30205596/204061637-1ecdc27d-89fb-48de-9cdd-d85fdb24808d.webm)

**Comment by domaingood** [comment]
Now I have fix issue Why dont show Error by Email/message. Domain is now registed. Domain Option Missing

![203976299-b7ea1a98-7a48-4fdc-a87d-fa8774d03c18](https://user-images.githubusercontent.com/30205596/204061674-82ecd427-d936-4066-a6d3-6a671e18db71.png)
[Client-1500-Manage-Service-My-Company.webm](https://user-images.githubusercontent.com/30205596/204061683-271b897e-854d-4c3b-a281-798ffbbc0d6a.webm)
[Dashboard-My-Company.webm](https://user-images.githubusercontent.com/30205596/204061688-f9c99b58-529b-4ede-8568-d9fe0c1a1c7b.webm)

**Comment by KaiSchwarz-cnic** [comment]
Please always create a new issue per case. Othewise threads are getting messed up.
