### ISSUE TITLE
Blesta ISPAPI registrar module Domain Manager Missing

### ISSUE THREAD

**Issue by zahid-10corp** [centralnicgroup-opensource/rtldev-middleware-blesta-ispapi-registrar#104]
I tried to install the Blesta ISPAPI registrar module and I register a Domain now Domain Card missing from the Admin+Client Dashboard Also When try to manage the domain I m getting the error HTTP ERROR 500
Please take a look.

https://user-images.githubusercontent.com/116925641/204062941-557b18f7-5e0c-44ea-8b8d-401f75193cec.mp4

**Comment by KaiSchwarz-cnic** [comment]
This will take a while, therefore let me ask you for a bit of patience.

**Comment by KaiSchwarz-cnic** [comment]
Hi there,

sry, it really took a while as I am not that familiar with blesta.

The error that we see here on our end, isn't directly related to our integration

(we switched to `Configure::errorReporting(-1);` in config/blesta.php for more transparency regarding php errors)

```
Uncaught TypeError, code 0 in /var/www/html/blesta/vendors/minphp/date/src/Date.php on line 459 Message: DateTime::__construct() expects parameter 1 to be string, array given
```

No idea about the origin of this error, at least it isn't coming from our integration while it is occuring.
Let me open a ticket at blesta.com

**Comment by KaiSchwarz-cnic** [comment]
v3.10.0 is patching this.

HTH
